### ISSUE TITLE
Unbound variable `allow_diff_regex` (when using `set -u`)

### ISSUE THREAD

**Issue by MPV** [DannyBen/approvals.bash#10]
Could we change approvals.bash to avoid errors like:
`approvals.bash: line 12: allow_diff_regex: unbound variable`

For example when sourcing and running the `approvals` function in a script which has:

```bash
set -u
source approvals.bash
approve "ls"
```

Another way to reproduce:

```bash
bash-5.2$ set -u
bash-5.2$ source approvals.bash
bash-5.2$ approve "ls"
bash: allow_diff_regex: unbound variable

Finished with failures
bash-5.2$ echo $?
1
```
---
On what `set -u` does:
- https://linuxcommand.org/lc3_man_pages/seth.html
- https://pubs.opengroup.org/onlinepubs/9699919799.2018edition/utilities/V3_chap02.html#set

**Comment by DannyBen** [comment]
Try now.

**Comment by MPV** [comment]
Works like a charm! 🙏 

Would you be up for releasing it as `0.4.2` (or equivalent)?

**Comment by DannyBen** [comment]
Done. Thanks for the report.

**Comment by MPV** [comment]
> Done. Thanks for the report.

Thanks for the quick assist. 😍
