### ISSUE TITLE
Auto-approving

### ISSUE THREAD

**Issue by MPV** [DannyBen/approvals.bash#13]
Hi,
Would you be up for adding/supporting a feature of auto-approving new changes?

Imagine a scenario:
1. You have plenty of tests and you make a change which includes approving many changes
3. Some changes may even mean that "some approvals (files) should be removed and others created".

Which may mean:
1. You make your change and would want to just approve all changes.
2. You might even want to be able to:
   1. `rm -rf approvals/`
   2. Rerun your `approvals.bash` tests
   3. Have all changes be auto-approved.

**Comment by DannyBen** [comment]
Absolutely.

In fact, I [have the same feature](https://github.com/dannyben/rspec_approvals/?tab=readme-ov-file#auto_approve) in the more mature Ruby version of this approval testing library.

Let me see if I can implement it here - should not be a problem.

**Comment by MPV** [comment]
Hah, nice to see I was on a track that made sense. And thanks for really quick feedback and help. ❤️

**Comment by DannyBen** [comment]
Merged. Thanks for the suggestion :)

**Comment by MPV** [comment]
Lovely. Will you make a release also? 🙏🏻

**Comment by DannyBen** [comment]
Of course. I am just working on another small update:

1. Adding `it` annotation, so we have the full "rspec compatible" context -> describe -> it chain
2. Reducing the color cacophony and changing all annotations to something unified.

Will be released today.

**Comment by DannyBen** [comment]
v0.5.1 is released.

If you have additional suggestions or issues, feel free to open another issue.
